name: Semgrep Findings

on:
  push:
    branches:
      - master

jobs:
  semgrep-scan:
    name: Semgrep-Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Semgrep (if using Pro/Enterprise)
        run: semgrep login --api-key ${{ secrets.SEMGREP_API_KEY }}
        env:
          SEMGREP_API_KEY: ${{ secrets.SEMGREP_API_KEY }}
        if: env.SEMGREP_API_KEY != ''

      - name: Run Semgrep Scan
        run: |
          semgrep scan --json --json-output /tmp/semgrep.json

      - name: Capture GitHub Metadata
        run: |
          jq -n \
            --arg repo "${{ github.repository }}" \
            --arg sha "${{ github.sha }}" \
            --arg ref "${{ github.ref }}" \
            --arg run_id "${{ github.run_id }}" \
            --arg run_number "${{ github.run_number }}" \
            --arg repo_url "${{ github.server_url }}/${{ github.repository }}" \
            --arg repo_run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            '{
              repo: $repo,
              sha: $sha,
              ref: $ref,
              run_id: $run_id,
              run_number: $run_number,
              repo_url: $repo_url,
              repo_run_url: $repo_run_url
            }' > /tmp/metadata.json

          jq -s '.[0] + .[1]' /tmp/metadata.json /tmp/semgrep.json > /tmp/semgrep_output.json

      - name: View the Output
        run: cat /tmp/semgrep_output.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /tmp/semgrep_output.json

      - name: Extract Organization Name
        run: |
          ORG_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          echo "Organization Name: $ORG_NAME"
